apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :8081
metrics:
  # rbac-proxy with tls? use 127.0.0.1:8080 as bind address
  # see config/default/manager_auth_proxy_patch.yaml
  bindAddress: 0.0.0.0:8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: 7230ddce.topicus.nl
