# permissions for end users to view keyhubsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keyhubsecret-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
- apiGroups:
  - keyhub.topicus.nl
  resources:
  - keyhubsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keyhub.topicus.nl
  resources:
  - keyhubsecrets/status
  verbs:
  - get
