# permissions for end users to edit keyhubsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keyhubsecret-editor-role
rules:
- apiGroups:
  - keyhub.topicus.nl
  resources:
  - keyhubsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keyhub.topicus.nl
  resources:
  - keyhubsecrets/status
  verbs:
  - get
