---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - keyhub.topicus.nl
  resources:
  - keyhubsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keyhub.topicus.nl
  resources:
  - keyhubsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - keyhub.topicus.nl
  resources:
  - keyhubsecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
