apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: keyhub-vault-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KeyHubSecret is the Schema for the keyhubsecrets API
      displayName: Key Hub Secret
      kind: KeyHubSecret
      name: keyhubsecrets.keyhub.topicus.nl
      version: v1alpha1
  description: '-'
  displayName: KeyHub Vault Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - '-'
  links:
  - name: Keyhub Vault Operator
    url: https://keyhub-vault-operator.domain
  maturity: alpha
  provider:
    name: '-'
    url: '-'
  version: 0.0.0
