name: Build

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths-ignore: [ ".github/workflows/release.yml" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set build vars
      id: set-build-vars
      run: |
        if [ ${{ github.ref }} == 'refs/heads/main' ]; then
          echo "RELEASE_VERSION=latest" >> $GITHUB_ENV
        else
          echo "RELEASE_VERSION=dev" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "./go.mod"

    - name: Login to GitHub Container Registry
      if: env.RELEASE_VERSION != 'dev'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      run: make docker-build
      env:
        IMG: ghcr.io/topicuskeyhub/keyhub-vault-operator:${RELEASE_VERSION}

    - name: Push image to GitHub Container Registry
      if: env.RELEASE_VERSION != 'dev'
      run: make docker-push
      env:
        IMG: ghcr.io/topicuskeyhub/keyhub-vault-operator:${RELEASE_VERSION}
