name: Renovate

on:
  - workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.6.0
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update dependencies
        uses: renovatebot/github-action@v32.154.7
        with:
          configurationFile: .github/renovate.json5
          token: 'x-access-token:${{ steps.generate_token.outputs.token }}'
        env:
          LOG_LEVEL: 'debug'
