name: Renovate

on:
  schedule:
    - cron: "0/20 0-6 * * 0,6"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@0d49dd721133f900ebd5e0dff2810704e8defbc6 # v1.8.2
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update dependencies
        uses: renovatebot/github-action@3cef36a9aba515d8726b491905b3bc766832e221 # v39.0.5
        with:
          configurationFile: .github/renovate.json5
          token: '${{ steps.generate_token.outputs.token }}'
        env:
          LOG_LEVEL: 'debug'
